CREATE DATABASE IF NOT EXISTS crud;
USE crud;
CREATE TABLE IF NOT EXISTS usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    fone VARCHAR(15) NOT NULL,
    data_nascimento DATE NOT NULL
);
